### ISSUE TITLE
Yowsup CLI always display "general: Disconnected: Connection Closed" when try to login

### ISSUE THREAD

**Issue by techmentalist** [tgalal/yowsup#2560] opened 2018-08-22 11:40 UTC
Hello, I have try to login into yowsup cli after successfully register my number. I am sure I have inserted the right combination of username and password. My steps is:
1. Registration my whatsapp number to get password 
code:
python yowsup-cli registration --requestcode sms --phone 91xxxxxxxxxx --cc 91 --mcc 222 --mnc 10 -E android       
2. Make a config file (vim config)
  cc="91" 
  phone="91xxxxxxxxxx"
  password="xxxxxxxxxxxxxxx="

3. Login to yowsup cli 
yowsup-cli demos --yowsup --config config

4. in terminal I type "/L"

the results are always like this no matter how many times I try to login.
 Do anybody know how to handle this problem?
Any help will be appreciated, thank you.

**Comment by 0rC0** [comment] 2018-08-25 08:47
Have you tried to register again and check if you were banned? See #2550.

**Comment by alexvong1995** [comment] 2018-08-27 18:15
Can anyone confirm that this bug is reproducible or unreproducible?

**Comment by gregroiusairlangga** [comment] 2018-09-01 15:26
I have checked , my number were not banned :)
still cannot login, i do not know why 
even I have changed the password, the result is displayed disconnected message rather than authorization error. any idea?

**Comment by powerzone3000** [comment] 2018-09-01 19:03
same issue here. Anything else we could try?

**Comment by alexvong1995** [comment] 2018-09-04 19:25
Have you tried updating `_MD5_CLASSES` and `_VERSION` and re-register
with a new number? I posted some instruction in #2566.

Also, I run yowsup using `python3` instead of `python`. Don't know if
this matter though.

**Comment by powerzone3000** [comment] 2018-09-05 16:46
thanks for your reply.
> Have you tried updating `_MD5_CLASSES` and `_VERSION` and re-register with a new number? I posted some instruction in #2566.

This was required to even get the number registered, and registration seemed to work fine afterwards.

I tried re-installing and running it using python3, but with the same error.

This is the output with parameter `--debug` (I anonymized some parts with X's):

    Yowsup Cli client
    ==================
    Type /help for available commands
    
    [offline]:/L
    DEBUG:yowsup.layers.network.layer:Connecting to e16.whatsapp.net:443
    DEBUG:yowsup.layers.logger.layer:tx:
    <stream:features>
    </stream:features>
    
    DEBUG:yowsup.layers.logger.layer:tx:
    <auth user="49XXXXXXXXXX" passive="true" mechanism="WAUTH-2">
    </auth>
    
    DEBUG:yowsup.layers.logger.layer:rx:
    <stream:features>
    </stream:features>
    
    DEBUG:yowsup.layers.logger.layer:rx:
    <challenge>
    t³�¸§�_XXXXXXXXXXX
    HEX3:b'74b391c308b8aXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    </challenge>
    
    DEBUG:yowsup.layers.logger.layer:tx:
    <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
    Y©�OXXXXXXX
    ÛE©fx^UjXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    HEX3:b'59a9874f70a80420XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    </response>
    
    DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
    general: Disconnected: Connection Closed
    [offline]:
    [offline]:

Seems like the handshake would fail and so WhatsApp would just close the connection?

**Comment by alexvong1995** [comment] 2018-09-05 23:47
powerzone3000 <notifications@github.com> writes:

> thanks for your reply.
>
>  Have you tried updating _MD5_CLASSES and _VERSION and re-register with a new
>  number? I posted some instruction in #2566.
>
> This was required to even get the number registered, and registration seemed to work fine
> afterwards.
>
Same for me, this was required for the registeration to work. Otherwise,
the 'old version' error will pop up.

> I tried re-installing and running it using python3, but with the same error.
>
> This is the output with parameter --debug (I anonymized some parts with X's):
>
> Yowsup Cli client
> ==================
> Type /help for available commands
>
> [offline]:/L
> DEBUG:yowsup.layers.network.layer:Connecting to e16.whatsapp.net:443
> DEBUG:yowsup.layers.logger.layer:tx:
> <stream:features>
> </stream:features>
>
> DEBUG:yowsup.layers.logger.layer:tx:
> <auth user="49XXXXXXXXXX" passive="true" mechanism="WAUTH-2">
> </auth>
>
> DEBUG:yowsup.layers.logger.layer:rx:
> <stream:features>
> </stream:features>
>
> DEBUG:yowsup.layers.logger.layer:rx:
> <challenge>
> t³�¸§�_XXXXXXXXXXX
> HEX3:b'74b391c308b8aXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> </challenge>
>
> DEBUG:yowsup.layers.logger.layer:tx:
> <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
> Y©�OXXXXXXX
> ÛE©fx^UjXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> HEX3:b'59a9874f70a80420XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> </response>
>
> DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
> general: Disconnected: Connection Closed
> [offline]:
> [offline]:
>
> Seems like the handshake would fail and so WhatsApp would just close the connection?
>
Is it possible that you have some files in your '~/.yowsup' directory
removed? I previously had mine deleted and then yowsup failed with a
similar message. So I registered with a fresh number and it worked
again.

Another possibilities is that your ip is being blocked.

For the record, registration / login still works for me as of early
September. So there is still hope.

**Comment by stv0g** [comment] 2019-05-01 10:38
@techmentalist Have you tried @alexvong1995 suggestions?

Please close the issue if you are not following this anymore.

**Closed** 2019-05-08 16:09 UTC
