### ISSUE TITLE
Send image

### ISSUE THREAD

**Issue by 546133753** [tgalal/yowsup#2757] opened 2019-05-17 06:40 UTC
when try send a image, display the next error:
    WARequest.__init__(self)
TypeError: __init__() tasks exactly 2 arguments (1 given)

**Comment by tgalal** [comment] 2019-05-17 06:41
duplicate of dozens of other still open issues. Sending media is broken and will be fixed soon

**Closed by tgalal** 2019-05-17 06:41 UTC

**Comment by 546133753** [comment] 2019-05-17 07:11
OK,Thanks
