### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/home/ilya/.config/yowsup'

### ISSUE THREAD

**Issue by Gnomeofoffice** [tgalal/yowsup#2695] opened 2019-04-26 18:05 UTC
![problem](https://user-images.githubusercontent.com/50028471/56827016-4b40c680-6866-11e9-8eec-57c269d4b954.png)

Hello, respect to the developers! I'm trying to install Whatsup using yowsup - not very experienced. Sim card is already registered in Whatsup. How can this problem be solved? Screen attached.

**Comment by Sharissa90** [comment] 2019-04-26 18:08
try chmod 777 /home/ilya/.config/yowsup

**Comment by Gnomeofoffice** [comment] 2019-04-28 08:25
Did not work.
Using mc looked on the file or folder in yowsup directory .config - not found. 
Created a folder In yowsup command line entered chmod 777 /home/ilya/.config/yowsup. Successfully. Then again, trying to register through the above line, again the same error.

**Comment by Gnomeofoffice** [comment] 2019-04-28 08:27
maybe the fact that the SIM card is already registered in whatsup? tell me please really need help with this misunderstanding.

**Comment by BodduSatya** [comment] 2019-04-28 08:49
use sudo before command

**Comment by Gnomeofoffice** [comment] 2019-04-28 09:03
![23464567534](https://user-images.githubusercontent.com/50028471/56861824-7aae1b00-69ad-11e9-9492-9b369fa8eb24.png)
did not help to solve the problem

**Comment by stv0g** [comment] 2019-05-01 10:35
This is a configuration error of your permissions and is not caused by yowsup.

Please close this issue.

**Comment by zablah** [comment] 2019-05-20 07:48
try chown -R ilya:ilya  /home/ilya/.config

**Closed** 2019-05-21 15:47 UTC
