### ISSUE TITLE
Message Send , But Not Received

### ISSUE THREAD

**Issue by jordhanbinnoushad** [tgalal/yowsup#2634] opened 2019-01-18 11:03 UTC
**Describe the bug**
Everythings Work fine except the message is not received in the other end

**To Reproduce**
Configure the yowsup,
Then try sending a message to someone.

No error when sending message. Tried catching exceptions in the whatsapp.py file , still there is no error or exceptions.But the message is not received at the user end

**Comment by 0x1999** [comment] 2019-01-19 00:00
I got same issue, i think my script error, but i register new number, i can send again, i guest the number has been banned

**Comment by marcoarildo** [comment] 2019-01-21 20:50
Hi, guys.

The same thing happened to me.
I just installed yowsup, set up the cell phone, received the code and triggered the confirmation and received the password.
But when I send a message it is not received from the other side and I also do not receive any error messages.

I created a new virtual machine with CentOS Linux release 7.3.1611 (Core)):

```
# sudo su - root
# cd /
# yum -y install epel-release
# yum -y install python-pip
# yum -y install gcc
# yum -y install python-devel libxslt-devel libffi-devel openssl-devel
# yum -y install git
# git clone git://github.com/tgalal/yowsup.git
# pip install yowsup2
# cd /yowsup
# python setup.py install

-- I changed the file yowsup/env/env.py:
	DEFAULT = "android"
-- I changed the file yowsup/env/env_android.py:
	_MD5_CLASSES = "0R9F4U5fzdwVvn06wLe1JA=="
	_VERSION = "2.18.255"

# cd /yowsup	
# python2.7 yowsup-cli registration -r sms -c config2
# python2.7 yowsup-cli registration -R 999-999 -c config2

INFO:yowsup.common.http.warequest:{"status":"ok","login":"5511999999999","type":"new","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","pw":"qDEGdwv/4NfKoDQ9/RRMdJTjmko=","expiration":4444444444.0,"kind":"free","price":"$0.99","cost":"0.99","currency":"USD","price_expiration":1548703077}
status: ok
kind: free
pw: qDEGdwv/4NfKoDQ9/RRMdJTjmko=
price: $0.99
price_expiration: 1548703077
currency: USD
cost: 0.99
expiration: 4444444444.0
login: 5511930542934
type: new


-- I put the password in the file config2
[root@Vm03Marco yowsup]# python2.7 yowsup-cli demos -c config2 -s 5511988888888 "hi marco." -M

yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

[root@Vm03Marco yowsup]#
```

It looks like the message is sent but it does not reach the destination.

**Comment by iamnibin** [comment] 2019-01-22 04:17
I am also getting the same issue I can see the log as below:

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

**Comment by marcoarildo** [comment] 2019-01-22 20:39
I repeated the steps again and after installation I ran the registry using android.

```
# python yowsup-cli registration -E android -r sms -c config2
# python yowsup-cli registration -E android -R 765-480 -c config2

-- result
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"ok","login":"55119xxxxxxxx","type":"new","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","pw":"QOTzrGAkL+R1KHDXFuOl90HNW7I=","expiration":4444444444.0,"kind":"free","price":"$0.99","cost":"0.99","currency":"USD","price_expiration":1548792727}

status: ok
kind: free
pw: QOTzrGAkL+R1KHDXFuOl90HNW7I=
price: $0.99
price_expiration: 1548792727
currency: USD
cost: 0.99
expiration: 4444444444.0
login: 55119xxxxxxxx
type: new
```

So, I tried so send a message using "s40", like this:

```
[root@Vm03Marco yowsup]# python yowsup-cli demos -E s40 -c config2 -s 5511999999999 "hi zapzap" -M
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.demos.sendclient.layer:Message sent

Yowsdown
[root@Vm03Marco yowsup]#
```
But, the message never arrive to destination and after some repetitions my number is banned.

Please @tgalal or somebody, can help me ?

**Comment by strannik-j** [comment] 2019-01-25 16:10
I have the same problem

**Comment by rafaelbusonid** [comment] 2019-02-01 19:34
@jordhanbinnoushad , Can you send message in 's40'? I have the error "Disconnected, reason: Connection Closed"

**Comment by tgalal** [comment] 2019-05-31 05:29
closing for lack of information and non-reproducibility

**Closed by tgalal** 2019-05-31 05:29 UTC
