### ISSUE TITLE
Old Version Error status: fail reason: old_version

### ISSUE THREAD

**Issue by syedmustafa54** [tgalal/yowsup#2237] opened 2017-09-07 08:14 UTC
# **Any One Here Can help me out Trying from 3 day still the same error nothing is working i tryed https://github.com/tgalal/yowsup/issues/2090 also not working**
` python yowsup-cli registration -E android  --requestcode sms --env android --phone 91*********--cc 91 --mcc 405 --mnc 025
INFO:yowsup.common.http.warequest:{"login":"91*********","status":"fail","reason":"old_version"}

yowsup-cli  v2.0.15
yowsup      v2.5.2

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

status: fail
reason: old_version
login: 91*********
`

**Comment by victor141516** [comment] 2017-09-07 10:49
Use [this](https://github.com/mgp25/classesMD5-64/blob/master/dexMD5.py) with the [latest version of WhatsApp APK](https://www.whatsapp.com/android/), you have to write that in the [env_android.py](https://github.com/tgalal/yowsup/blob/master/yowsup/env/env_android.py) (replacing `_MD5_CLASSES` and `_VERSION` vars) then run:
`python setup.py build`
`python setup.py install`

If you have installed yowsup using pip, you shuold uninstall it first (`pip uninstall yowsup`) then run build and install.

**Comment by jnoam** [comment] 2017-09-09 06:33
still not working even with  _VERSION = "2.12.556"

Any ideas?

**Comment by dezember** [comment] 2017-09-09 08:49
@jnoam After following the steps mentioned by @victor141516 try following:

open file: yowsup/env/__init__.py

Comment the third line:
`#from .env_s40 import S40YowsupEnv
` 
This will force registration to use android_env file.

**Comment by BRNALX** [comment] 2017-09-12 18:33
@syedmustafa54  Try this:

file: env_android.py
class: AndroidYowsupEnv

  _SIGNATURE = "MIIDMjCCAvCgAwIBAgIETCU2pDALBgcqhkjOOAQDBQAwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFDASBgNV" \
        "BAcTC1NhbnRhIENsYXJhMRYwFAYDVQQKEw1XaGF0c0FwcCBJbmMuMRQwEgYDVQQLEwtFbmdpbmVlcmluZzEUMBIGA1UEAxMLQnJ" \
        "pYW4gQWN0b24wHhcNMTAwNjI1MjMwNzE2WhcNNDQwMjE1MjMwNzE2WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5" \
        "pYTEUMBIGA1UEBxMLU2FudGEgQ2xhcmExFjAUBgNVBAoTDVdoYXRzQXBwIEluYy4xFDASBgNVBAsTC0VuZ2luZWVyaW5nMRQwEg" \
        "YDVQQDEwtCcmlhbiBBY3RvbjCCAbgwggEsBgcqhkjOOAQBMIIBHwKBgQD9f1OBHXUSKVLfSpwu7OTn9hG3UjzvRADDHj+AtlEm" \
        "aUVdQCJR+1k9jVj6v8X1ujD2y5tVbNeBO4AdNG/yZmC3a5lQpaSfn+gEexAiwk+7qdf+t8Yb+DtX58aophUPBPuD9tPFHsMCN" \
        "VQTWhaRMvZ1864rYdcq7/IiAxmd0UgBxwIVAJdgUI8VIwvMspK5gqLrhAvwWBz1AoGBAPfhoIXWmz3ey7yrXDa4V7l5lK+7+jr" \
        "qgvlXTAs9B4JnUVlXjrrUWU/mcQcQgYC0SRZxI+hMKBYTt88JMozIpuE8FnqLVHyNKOCjrh4rs6Z1kW6jfwv6ITVi8ftiegEkO" \
        "8yk8b6oUZCJqIPf4VrlnwaSi2ZegHtVJWQBTDv+z0kqA4GFAAKBgQDRGYtLgWh7zyRtQainJfCpiaUbzjJuhMgo4fVWZIvXHaS" \
        "HBU1t5w//S0lDK2hiqkj8KpMWGywVov9eZxZy37V26dEqr/c2m5qZ0E+ynSu7sqUD7kGx/zeIcGT0H+KAVgkGNQCo5Uc0koLRW" \
        "YHNtYoIvt5R3X6YZylbPftF/8ayWTALBgcqhkjOOAQDBQADLwAwLAIUAKYCp0d6z4QQdyN74JDfQ2WCyi8CFDUM4CaNB+ceVXd" \
        "KtOrNTQcc0e+t"

    _MD5_CLASSES = "ox998VW0nBTueMVfjuZkmQ=="
    _KEY = "eQV5aq/Cg63Gsq1sshN9T3gh+UUp0wIw0xgHYT1bnCjEqOJQKCRrWxdAe2yvsDeCJL+Y4G3PRD2HUF7oUgiGo8vGlNJOaux26k+A2F3hj8A="

    _VERSION = "2.17.212"
    _OS_NAME = "Android"
    _OS_VERSION = "4.3"
    _DEVICE_NAME = "armani"
    _MANUFACTURER = "Xiaomi"
    _BUILD_VERSION = "JLS36C"
    _AXOLOTL = True

----------------------------------------------------------

Get the sms cod and registre yow number with env android, but, the yowsup login change env for s40.

**Comment by oxydaemon** [comment] 2017-09-16 08:21
BRNALX thx bro, you saved me some time :-)
Works for me👍

**Comment by BRNALX** [comment] 2017-09-16 14:05
@syedmustafa54 works for you?

Please close this issue.

**Comment by hmrasi** [comment] 2017-11-20 12:07
need some help regarding the axolotl curve.
I'm getting the error as 
NoModuleFoundError : No Module named 'Axolotl_Curve25519'

anyone please help me?

**Comment by BRNALX** [comment] 2017-11-20 17:23
@hmrasi 


It worked normal and this error started to appear now?

This seems to be a problem in the installation. Problems we faced when we started working with YowSup

Please tell us more about your problem.

**Comment by hmrasi** [comment] 2017-11-24 12:23
![capture12](https://user-images.githubusercontent.com/33692337/33210388-05b29562-d140-11e7-8c42-701afe7a12a4.PNG)


this is what i'm getting.
i have tried it in many ways to resolve. I installed the axolotl_curve25519 again and then started doing the steps in the readme file. Even i'm getting the same error.
How can i login again with the same code and send a message?

**Comment by BRNALX** [comment] 2017-11-24 17:42
@hmrasi 

in your console, execute pip install yowsup2.

How is return?

**Comment by hmrasi** [comment] 2017-11-27 04:30
![capture14](https://user-images.githubusercontent.com/33692337/33250932-9df4ee18-d359-11e7-9f32-24d1499e32c1.PNG)


Yeah i already did the same. getting the same after doing so. Here is  the error while i'm trying to install Yowsup2 using pip.

**Comment by BRNALX** [comment] 2017-11-27 12:25
@hmrasi 

The problem is very clear, install Microsoft Visual C ++ 14.0.

And rerun pip install yowsup2

**Comment by hmrasi** [comment] 2017-11-27 13:40
Can u give me the steps to follow?
Or any path i have to mention for that one? I mean environmental path
Or directly i have to place in the python folder?

**Comment by BRNALX** [comment] 2017-11-27 19:10
@hmrasi 

your problem is not yowsup or python. Your problem is install prereqs for yowsup work.

steps to follow? Well,  install Microsoft Visual C ++ 14.0., and after install yowsup with (pip install yowsup2).

**Comment by hmrasi** [comment] 2017-11-28 05:10
![error now](https://user-images.githubusercontent.com/33692337/33303296-5f6e376a-d428-11e7-9bcd-888a41505c0a.PNG)


still getting the same error while installing yowsup2. 
Help me with that!

**Comment by hmrasi** [comment] 2017-12-04 11:16
@BRNALX 
Help me with that!!!!

**Comment by BRNALX** [comment] 2017-12-04 13:50
@hmrasi 

Do you have this dll (msvcp140.dll) in your folder system32?

Try again step by step for install yowsup.

**Closed** 2019-05-08 15:51 UTC
