### ISSUE TITLE
cant send none English msg

### ISSUE THREAD

**Issue by markayala646** [tgalal/yowsup#2735] opened 2019-05-09 21:33 UTC
cant send none English msg , when i send one cli close.

**Comment by tgalal** [comment] 2019-05-09 21:36
post debug logs, error message, how are you sending, how to reproduce, otherwise no help

**Comment by danielct59** [comment] 2019-05-11 12:57
Aroot@mk-authyowsup-cli demos --config-phone 5588988689819:mHPlzABuYYXALm0XVlJzvbScrHpeOJsH0B8vnhhFJXUAeHZb4bOI2bXVYG79evEH/KoSoklw3cKrjkgLO8UReg== -e
E 2019-05-11 09:54:56,672 yowsup.config.manager - Could not find a config for username=5588988689819:mHPlzABuYYXALm0XVlJzvbScrHpeOJsH0B8vnhhFJXUAeHZb4bOI2bXVYG79evEH/KoSoklw3cKrjkgLO8UReg==, paths checked: /root/.config/yowsup/5588988689819:mHPlzABuYYXALm0XVlJzvbScrHpeOJsH0B8vnhhFJXUAeHZb4bOI2bXVYG79evEH/KoSoklw3cKrjkgLO8UReg==/config.yo:/root/.config/yowsup/5588988689819:mHPlzABuYYXALm0XVlJzvbScrHpeOJsH0B8vnhhFJXUAeHZb4bOI2bXVYG79evEH/KoSoklw3cKrjkgLO8UReg==/config.json
yowsup-cli  v3.2.0
yowsup      v3.2.3

Copyright (c) 2012-2019 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


I 2019-05-11 09:54:58,158 yowsup.layers.network.layer - Connecting to e5.whatsapp.net:443
I 2019-05-11 09:54:59,216 yowsup.axolotl.manager - Generating 812 prekeys
I 2019-05-11 09:55:01,223 yowsup.axolotl.manager - Storing 812 prekeys
I 2019-05-11 09:57:01,115 yowsup.axolotl.manager - Loaded 812 unsent prekeys
E 2019-05-11 09:57:01,132 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/usr/lib/python3.4/asyncore.py", line 460, in handle_write_event
    self.handle_connect_event()
  File "/usr/lib/python3.4/asyncore.py", line 448, in handle_connect_event
    self.handle_connect()
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 34, in handle_connect
    self.connectionCallbacks.onConnected()
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/network/layer.py", line 53, in onConnected
    self.emitEvent(YowLayerEvent(YowNetworkLayer.EVENT_STATE_CONNECTED))
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 94, in emitEvent
    self.__upper.emitEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 88, in emitEvent
    if self.__upper and not self.__upper.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 212, in onEvent
    stopEvent = stopEvent or s.onEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/auth/layer_authentication.py", line 36, in on_connected
    passive=self.getProp(self.PROP_PASSIVE, False)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 202, in subBroadcastEvent
    self.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 103, in broadcastEvent
    self.__lower.broadcastEvent(yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 98, in broadcastEvent
    if self.__lower and not self.__lower.onEvent(yowLayerEvent):
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/__init__.py", line 109, in onEvent
    return self.event_callbacks[eventName](yowLayerEvent)
  File "/usr/local/lib/python3.4/dist-packages/yowsup-3.2.3-py3.4.egg/yowsup/layers/noise/layer.py", line 57, in on_auth
    self._username, local_static = int(credentials[0]), credentials[1]
ValueError: invalid literal for int() with base 10: '5588988689819:mHPlzABuYYXALm0XVlJzvbScrHpeOJsH0B8vnhhFJXUAeHZb4bOI2bXVYG79evEH/KoSoklw3cKrjkgLO8UReg=='

**Comment by karimQasem** [comment] 2019-05-16 14:31
i am sending message arabic with git Bash terminal try it

**Comment by dkdndes** [comment] 2019-05-16 16:48
How shall somebody in Europe have a clue how to do that. Provide the python script you used, and a explanation of the python version you used, and which operating system

**Comment by tgalal** [comment] 2019-06-04 15:29
can't reproduce, or has been fixed. closing for lack of information

**Closed by tgalal** 2019-06-04 15:29 UTC
