### ISSUE TITLE
Registered with success, the Message was sent with sucess but is not received.

### ISSUE THREAD

**Issue by marcoarildo** [tgalal/yowsup#2636] opened 2019-01-23 13:51 UTC
Hi, guys.

I got "old_version" too, so after read a lot of Issues on this "yowsup", i understood i had to do this.

I did a complete instation again using a new virtual machine but when I try sent a message i have got success but the message is not received by the other celphone number.

Bellow, you can see i my complete instalation.

I created a new virtual machine with CentOS Linux release 7.3.1611 (Core)):

```
# sudo su - root
# cd /
# yum -y install epel-release
# yum -y install python-pip
# yum -y install gcc
# yum -y install python-devel libxslt-devel libffi-devel openssl-devel
# yum -y install git
# git clone git://github.com/tgalal/yowsup.git
# pip install yowsup2

-- I changed the file yowsup/env/env.py:
	DEFAULT = "android"
-- I changed the file yowsup/env/env_android.py:
	_MD5_CLASSES = "0R9F4U5fzdwVvn06wLe1JA=="
	_VERSION = "2.18.255"
# cd /yowsup
# python setup.py install


-- I created the file "config2" like that:
[root@Vm03Marco yowsup]# cat config2
cc=55
phone=5511988888888
id=
password=

-- Now I will send a registration using config2 and "android"

[root@Vm03Marco yowsup]# python yowsup-cli registration -r sms -c config2 -E android

yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"login":"5511988888888","status":"fail","reason":"incorrect","sms_length":6,"voice_length":6,"sms_wait":0,"voice_wait":0}

INFO:yowsup.common.http.warequest:{"login":"5511988888888","status":"sent","length":6,"method":"sms","retry_after":116,"sms_wait":116,"voice_wait":65}

status: sent
retry_after: 116
length: 6
login: 5511988888888
method: sms
[root@Vm03Marco yowsup]#

-- Now I will send message using the received code on celphone "524-973" and with "android" to finish the registration.

[root@Vm03Marco yowsup]# python yowsup-cli registration -R 524-973 -c config2 -E android
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"ok","login":"5511988888888","type":"new","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","pw":"8o/Y/cbQiZUSKY8uBiA4Kdom0Sc=","expiration":4444444444.0,"kind":"free","price":"$0.99","cost":"0.99","currency":"USD","price_expiration":1548855071}

status: ok
kind: free
pw: 8o/Y/cbQiZUSKY8uBiA4Kdom0Sc=
price: $0.99
price_expiration: 1548855071
currency: USD
cost: 0.99
expiration: 4444444444.0
login: 5511988888888
type: new

[root@Vm03Marco yowsup]#

-- I put the password in the file "config2", like that:
[root@Vm03Marco yowsup]# cat config2
cc=55
phone=5511988888888
id=
password=8o/Y/cbQiZUSKY8uBiA4Kdom0Sc=
[root@Vm03Marco yowsup]#

-- Now I will will try to send a message, using the "s40"

[root@Vm03Marco yowsup]# python yowsup-cli demos -E s40 -c config2 -s 5511977777777 "hello marco." -M
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


Authentication Error: not-authorized
[root@Vm03Marco yowsup]#

```

Guys, yesterday I did this steps and i got sucess when i tried to send message, because i received the "INFO:yowsup.demos.sendclient.layer:Message sent", 
but the message not was received by the other celphone number. 

Today i received the "Authentication Error: not-authorized" at the first try.

Somebody have ideia how to fix this ? Somebody is having success using yowsup in this moment ?

My yowsup has been stopped since 2 weeks.

Thank you guys and have a nice day.

**Comment by alexvong1995** [comment] 2019-01-23 13:56
Please see #2635. It seems everyone receives some errors.

**Comment by lexs2kari** [comment] 2019-01-23 15:31
@marcoarildo 

Same issue here.
Updating the android env version lets me to register new numbers, but not send messages.

**Comment by marcoarildo** [comment] 2019-01-23 15:59
Hi @lexs2kari

I updated the files below, as was said in this forum:

file yowsup/env/env.py:
	DEFAULT = "android"
	
file yowsup/env/env_android.py:
	_MD5_CLASSES = "0R9F4U5fzdwVvn06wLe1JA=="
	_VERSION = "2.18.255"

After I set up the Virtual Machine and performed the installation procedures I was able to successfully register the number using the commands below:

```
# python yowsup-cli registration -r sms -c config2 -E android
# python yowsup-cli registration -R 524-973 -c config2 -E android
```

Then I tried to send the message using "-E s40" as below and I was banned.

```
# python yowsup-cli demos -E s40 -c config2 -s 5511977777777 "hello marco." -M
```

I confess I did not understand what other files I need to change.

Thank you again and sorry by my English.

**Comment by alexvong1995** [comment] 2019-01-23 16:28
Hello @marcoarildo

marcoarildo <notifications@github.com> writes:

> Hi @lexs2kari
>
> I updated the files below, as was said in this forum:
>
> file yowsup/env/env.py:
> DEFAULT = "android"
>
> file yowsup/env/env_android.py:
> _MD5_CLASSES = "0R9F4U5fzdwVvn06wLe1JA=="
> _VERSION = "2.18.255"
>
I think your md5 class and version are outdated. You need to follow the
instruction in #2566 and #2564 to get the latest one.

> After I set up the Virtual Machine and performed the installation procedures I was able to
> successfully register the number using the commands below:
>
> # python yowsup-cli registration -r sms -c config2 -E android
> # python yowsup-cli registration -R 524-973 -c config2 -E android
>
> Then I tried to send the message using "-E s40" as below and I was banned.
>
> # python yowsup-cli demos -E s40 -c config2 -s 5511977777777 "hello marco." -M
>
Why do you use
> -E s40
instead of
> -E android
?

I think this is why you get banned instantly. As mentioned by bahtiarp
in #2635, s40 is no longer support after December 31, 2018.

By the way, can you post the error message you've got?

**Comment by marcoarildo** [comment] 2019-01-23 20:47
Hi @alexvong1995

Thank you for help me.

I read the #2566 and #2564 and got new version of md5 class using https://coderus.openrepos.net/whitesoft/whatsapp_scratch

{
   "a": "5eItLCbGXx3CKpybxo81/A==",
   "b": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
   "c": "1478194306452L",
   "d": "2.19.15",
   "e": "2.16.12",
   "f": "2.11.634",
   "g": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
   "h": "1478194472015L",
   "i": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
   "j": "1478194472015L"
}

I took the 'a' for _MD5_CLASSES and 'd' for _VERSION and fix on env_android.py, like that

content file yowsup/env/env_android.py:

MD5_CLASSES = "5eItLCbGXx3CKpybxo81/A=="
_VERSION = "2.19.15"

After this I got a new celphone number and inicialized the configuration again:

```
[root@Vm03Marco /]# cd /yowsup

[root@Vm03Marco yowsup]# python setup.py install

[root@Vm03Marco yowsup]# python yowsup-cli registration -r sms -c config2

yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate

INFO:yowsup.common.http.warequest:{"login":"5511912345678","status":"sent","length":6,"method":"sms","retry_after":84,"sms_wait":84,"voice_wait":64}

status: sent
retry_after: 84
length: 6
login: 5511912345678
method: sms
[root@Vm03Marco yowsup]#
```
-- Completing the registration to get password
```
[root@Vm03Marco yowsup]# python yowsup-cli registration -R 327-034 -c config2
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


INFO:yowsup.common.http.warequest:{"status":"ok","login":"5511912345678","type":"new","edge_routing_info":"CAUIAg==","chat_dns_domain":"fb","pw":"tWiLJSgI3XC1k2KPrEzqMwCQBuE=","expiration":4444444444.0,"kind":"free","price":"$0.99","cost":"0.99","currency":"USD","price_expiration":1548867559}

status: ok
kind: free
pw: tWiLJSgI3XC1k2KPrEzqMwCQBuE=
price: $0.99
price_expiration: 1548867559
currency: USD
cost: 0.99
expiration: 4444444444.0
login: 5511912345678
type: new
[root@Vm03Marco yowsup]#
```
-- After changed the file config2 with the password
```
[root@Vm03Marco yowsup]# python yowsup-cli demos -E android -c config2 -s 5511966666666 "hi please works." -M
yowsup-cli  v2.0.15
yowsup      v2.5.7

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


[root@Vm03Marco yowsup]#
```

Analyzing the result did not show that the message was sent and neither was received by the other cell phone.

Anybody have some idea ?

**Comment by alexvong1995** [comment] 2019-01-24 17:20
Hi @marcoarildo

marcoarildo <notifications@github.com> writes:

[...]
>
> Analyzing the result did not show that the message was sent and neither was received by
> the other cell phone.
>
The situation you described is the same the one mentioned by HeinzFo in
<https://github.com/tgalal/yowsup/issues/2635#issuecomment-456825465>.
I suggest you to wait for responses in #2635.

You can also close this issue because it is a duplicate of #2635.

**Comment by marcoarildo** [comment] 2019-01-24 18:11
Thank you @alexvong1995 

I will close and wait for responses in #2635.

**Comment by marcoarildo** [comment] 2019-01-24 18:14
I am closing because Is the same situation like #2635

**Closed** 2019-01-24 18:14 UTC
