### ISSUE TITLE
Can't connect with yowsup-cli client

### ISSUE THREAD

**Issue by robertompr** [tgalal/yowsup#1313] opened 2016-02-16 16:37 UTC
Is there any issue with yowsup? 
When I try to connect to yowsup-cli client I get the answer "Disconnected: Connection Closed"

[offline](/L):

general: Disconnected: Connection Closed

But if I try to send an sms through command line it works well

I need to get into yowsup-cli client to get jid of some groups that I belong to

Thank you so much for your help
##

**Comment by jlguardi** [comment] 2016-02-16 16:43
Are you using two instances of yowsup running simultaneously?
If you run start a second instance of yowsup y will get this error. Yo can get this error also if y are ignoring acks. 

Anyway, attach debug log to the issue (start with -d flag).

**Comment by robertompr** [comment] 2016-02-16 17:05
Here is the Log. How can I know that I'm running two instances of yowsup? What command should I use? How can I know that I'm ignoring acks? What commands should I use?

Thank you so much for your answer


root@debian:~/yowsup# yowsup-cli demos --debug -c whatsapp_config.txt --yowsup
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e7.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="51972440883" mechanism="WAUTH-2">
{� h�Rײ�0>�l _U��{ Ϛ �j ����L�h�oGi�/=#��Tb
HEX:7b901d68d052d7b2d2303ecc6c045f55d8da7b14cf9a10aa6a14abbae9a04c9468a66f4769ed2f3d239da55462
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed
[offline]:
general: Disconnected: Connection Closed
[offline]:
[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e7.whatsapp.net:443
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="false" user="51972440883" mechanism="WAUTH-2">
r•=�Rײ�0>�l _U��{ Ϛ �j ����L�h�oGi�/=#��P`
HEX:72c2953dd052d7b2d2303ecc6c045f55d8da7b14cf9a10aa6a14abbae9a04c9468a66f4769ed2f3d239da45060
</auth>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

general: Disconnected: Connection Closed
[offline]:

general: Disconnected: Connection Closed
[offline]:
[offline]:

**Comment by sendytiaprayoga** [comment] 2016-09-29 02:33
i have same issue, i use yowsup v2.5.0.
i can register my number, but if i want to exec echo demo or send message always disconnected
any one can help?

**Comment by Nibikibaba** [comment] 2016-10-04 18:32
Same problem here. I am using 2.5.0 under Windows 10.
The registration process seems to be successful and I've received my password.
The command line send ended without errors but nothing is received from the other side. 
CLI is always [offline]. /L login would always produce: 
general: Disconnected: Connection Closed

Here are the debug logs:
> yowsup-cli demos -d -l 1647xxxxxxx:xxx....= -s 1234xxxx test
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x0345A1B0>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x03445E10>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed Interface Layer
DEBUG:yowsup.layers.network.layer:Connecting to e12.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="1647xxxxxxx" mechanism="WAUTH-2">
ƒ....╚ø
HEX:232a.....15ce
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
~¯Hn■...\õþÌf
HEX:7eee.....de66
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
toc­▒....Ù,¡
HEX:8736072b.....34051ef6041a
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

(Intereaction login: yowsup-cli demos -d -c config.txt -y)
yowsup-cli  v2.0.15
yowsup      v2.5.0

Copyright (c) 2012-2016 Tarek Galal
http://www.openwhatsapp.org

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://openwhatsapp.org/yowsup/donate


DEBUG:yowsup.env.env:Env not set, setting it to android
DEBUG:yowsup.env.env:Current env changed to android
DEBUG:yowsup.stacks.yowstack:Initializing stack
DEBUG:yowsup.stacks.yowstack:Constructed Network Layer
DEBUG:yowsup.stacks.yowstack:Constructed Stanza Regulator Layer
DEBUG:yowsup.stacks.yowstack:Constructed Crypt Layer
DEBUG:yowsup.stacks.yowstack:Constructed Coder Layer
DEBUG:yowsup.stacks.yowstack:Constructed Logger Layer
DEBUG:yowsup.stacks.yowstack:Constructed <yowsup.layers.axolotl.layer_control.AxolotlControlLayer object at 0x03650470>
DEBUG:yowsup.stacks.yowstack:Constructed Axolotl Layer - <yowsup.layers.axolotl.layer_receive.AxolotlReceivelayer object at 0x036500F0>
DEBUG:yowsup.stacks.yowstack:Constructed Authentication Layer - Messages Layer - Receipt Layer - Ack Layer - Presence Layer - Ib Layer - Iq Layer - notification Ib Layer - Iq Layer - Chatstate Layer - call Layer - Groups Iq Layer - Media Layer - Privacy Layer - Profiles Layer
DEBUG:yowsup.stacks.yowstack:Constructed CLI Interface Layer
Yowsup Cli client
==================
Type /help for available commands

[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e11.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="1647....." mechanism="WAUTH-2">
ƒ.....╬*╚ø
HEX:a558....15ce
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
ÙB░.....Àƒ|
HEX:eb42b0.....9b79f7c
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
ı‗m1J®.....j8╬äå
HEX:d5f2146d3......84861407
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed
[offline]:
[offline]:


Any suggestions?

Many thanks for the wonderful work.

**Comment by bashan** [comment] 2016-11-27 01:20
I have the same issue. Did anyone manage to overcome?

**Comment by devbox** [comment] 2016-12-11 12:30
Hi,
i also have this issue.
always get this debug message: 
DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed

my yowsup installation was a year old, so i decided to do the install steps again, to get the new version.
So how can i check, if a second yowsup instance is active, and how can i close it?

I also have a folder/opt/yowsup-Android_2.12.440 but doesn´t know what it was about. 

will be nice if someone can help, thx!

**Comment by vatam** [comment] 2016-12-12 17:13
Same issue here, anyone has a solution? Will be good to see help

**Comment by nervmaster** [comment] 2016-12-13 01:07
Same issue here.

On $./yowsup-cli demos --yowsup

I try to login - it takes some time - and it says connection closed. 
When I try with wrong phone/password it says Unauthorized Access. Otherwise just get connection closed upfront.

Using -d I got these lines:

> [offline]:/L
> DEBUG:yowsup.layers.network.layer:Connecting to e11.whatsapp.net:443
> DEBUG:yowsup.layers.logger.layer:tx:
> <stream:features>
> </stream:features>
> 
> DEBUG:yowsup.layers.logger.layer:tx:
> <auth passive="true" user="5<edited>97" mechanism="WAUTH-2">
> </auth>
> 
> DEBUG:yowsup.layers.logger.layer:rx:
> <stream:features>
> </stream:features>
> 
> DEBUG:yowsup.layers.logger.layer:rx:
> <challenge>
> So
> \=H
> HEX:e876f0af9ab6d7caf6eed1536f0a5c9f3d48df1a
> </challenge>
> 
> DEBUG:yowsup.layers.logger.layer:tx:
> <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
> X[@_zE:^b7?=2sO>zsr':
>                      J2)?e
> HEX:9cc1ad58ddc403125b405f7a9a45823a05fb5e90d0301c62f46fe98c78b7373f3d32734f3e191c90e758bbdcfeb87aa1aadc4a73af7227983ab8a7a70bdacaab124a3229adb2ae85e9ceec283f65
> </response>
> 
> DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
> general: Disconnected: Connection 
>

**Comment by rafaelsilverioit** [comment] 2016-12-13 11:02
1. Can you provide ping and tracert tests, please?
2. Run these commands and post the output here:
```$ openssl s_client -connect e11.whatsapp.net:443 | grep CONNECTED```
```$ openssl s_client -connect e12.whatsapp.net:443 | grep CONNECTED```

**Comment by harishkumarv** [comment] 2016-12-13 12:48
@rafaelsilverioit:

```
$ openssl s_client -connect e11.whatsapp.net:443
CONNECTED(00000003)
36798:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/ssl/s23_lib.c:185:
$ openssl s_client -connect e12.whatsapp.net:443 | grep CONNECTED
36831:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64/src/ssl/s23_lib.c:185:
CONNECTED(00000003)
```

**Comment by rafaelsilverioit** [comment] 2016-12-13 13:27
@nervmaster It is likely a firewall issue. Can you stop iptables (or whatever firewall you are using) and try again?

@harishkumarv Can you do the ping and traceroute tests, please?

**Comment by rafaelsilverioit** [comment] 2016-12-13 14:32
@nervmaster and @harishkumarv , it seems that I have missed the protocol, try again with `-dtls1` param.

Command: 
``` $ openssl s_client -dtls1 -connect e12.whatsapp.net:443 ```

For me it is throwing something like `XXXXXX:error:XXXXX:SSL routines:dtls1_check_timeout_num:read timeout expired:d1_lib.c:480`.

It is timing out, probably because the servers are offline. @tgalal and @jlguardi can you check it, please?

**Comment by cmeerw** [comment] 2016-12-13 14:38
What are you trying to test here? Those servers don't speak SSL
(https) on port 443 - they only expect the WhatsApp protocol...

**Comment by lbhack** [comment] 2017-01-04 21:49
i am ready for any help

**Comment by xhcardoza** [comment] 2017-02-22 21:04
Hello, same issue here, I've read and read but can no find any solution. What I'm missing? Please your help.

Best regards

**Comment by shubhamDTU007** [comment] 2017-02-24 11:12
Hello,
Facing same issue.
Registration process completed successfully but getting error while sending message.
Does anyone able to send/receive messages from yowsup?

@tgalal 
Would be glad if you can help!
Thanks


**Error Trace:**
[offline]:/L
DEBUG:yowsup.layers.network.layer:Connecting to e3.whatsapp.net:443
DEBUG:yowsup.layers.logger.layer:tx:
<stream:features>
<readreceipts>
</readreceipts>
<groups_v2>
</groups_v2>
<privacy>
</privacy>
<presence>
</presence>
</stream:features>

DEBUG:yowsup.layers.logger.layer:tx:
<auth passive="true" user="9188519XXXXX" mechanism="WAUTH-2">
</auth>

DEBUG:yowsup.layers.logger.layer:rx:
<stream:features>
</stream:features>

DEBUG:yowsup.layers.logger.layer:rx:
<challenge>
???"?$?+?2I?PqYt?
HEX:b4c3e58022f624f3bc2bf23249b75017715974bc
</challenge>

DEBUG:yowsup.layers.logger.layer:tx:
<response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
???g?+??v??V??)3?E??
                    ]??)?
                         ???xB???IpCu	%e?K??dTƴ?s????3?W??+2?֮?$?
HEX:c1f6bd6705882b9df476e7f856c4c129339645d2f10c5db4a629e00cf6c2d51f7842f98f874970437509250165b54b9dca645414c6b4e2738daaabe83304b60e57d517ae1d2b3210a9d6aeda24f5
</response>

DEBUG:yowsup.layers.network.layer:Disconnected, reason: Connection Closed
general: Disconnected: Connection Closed

**Comment by dthierbach** [comment] 2017-02-26 15:27
Same issue here. It recognizes login and password, because with a different login or password, I get "Auth Error, reason not-authorized" instead. So *something* works.

Any ideas how to proceed, or how to debug this?

**Comment by filipeferminiano** [comment] 2017-03-12 23:01
Same error here.
Some idea how to fix this?

**Comment by PatrickFelber** [comment] 2017-03-20 21:26
Hi all
with the following procedure I got yowsup running:
I used the current master of colonyhqs fork: https://github.com/colonyhq/yowsup
I set the environment to Android for registration, because I faced issues with the s40 environment (see #1962). After registration I faced the problems described here while trying to login or send messages. Thus I switched the environment back to s40 - now it's working...
Well obviously this can't be the solution, but maybe it helps somebody finding the root cause.

**Comment by brunodeandrade** [comment] 2017-05-23 13:18
Need help with this issue!

**Comment by Phyriphiry** [comment] 2017-07-08 10:15
I have the same issue.
What did I do?
I didn't succes in connecting with the right password and found somewhere that the S40 environment as from 30 june 2017 would not be supported by Whatsapp. So I installed everything as an Android environment.

This worked fine!

However, when I run the demos command line client, I cannot connect. "Connection Closed".
I run the CL client with following command:
yowsup-cli demos -E android -y -d --config mydetails

If I use it without the environment parameter, I get an autorisation error. This makes sense because my password was perceived in an android environment.

I learn from debug files that the whatsapp sends a "challenge" string and the yowsup client sends a hexadecimal response. On that response the client says "connection closed".

I think somehow there is still something wrong with the environment parameter...

Can someone help out?

P

**Comment by jlguardi** [comment] 2017-07-08 12:29
Android uses protocol wa20 which isn't implemmented by yowsup. So keep using s40 env.

**Comment by Phyriphiry** [comment] 2017-07-08 16:16
With s40 i get an authentication error. Another weird thing, everytime i register via yowsup, i have to re-register on my iPhone. It's like whatsapp knows you can only have one phone with the same number...

**Comment by fjrmaulana** [comment] 2017-12-15 02:21
hello sir, yowsup realy work or not today?

**Comment by lippih** [comment] 2018-01-23 16:01
Yes it works, but probably WhatsApp will ban your Phone-Number

**Closed** 2019-05-20 22:05 UTC
