### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by apdbsa** [tgalal/yowsup#786] opened 2015-05-10 01:42 UTC
First of all, the application you've done is amazing and useful.... (my english is awful) I am investigating how to make an application that more or less work with whatsapp for radio station ... In my tests now I blocked 3 simcards, probably by sending more (strange, because everything we have done with 50 test numbers of the company), or that I have not added to the agenda, in theory I follow the steps correctly to Sending and receiving
Can you answer the following ?:
- How many messages can I send per day ?, how many messages I receive each day?
- Reading, reaches the problem is also the reception, if you send many messages, regardless of whether you are on the agenda or not, you can also block ... this is so?
- What would be the limits imposed whatsapp according to your experience ...
  *A blocked number can again be useful in the future?

Thank you so much .... greetings
##

**Comment by mutindaz** [comment] 2015-05-10 16:21
Well, I don't know whether I will be able give a specific answer but I will give you some insights of what I  have used the library for. 

My application has [received] over 1 million messages within 3 weeks and for every received message there is always a [response] which means that I have achieved close to 2 million messages - both inbox and outbox and I my number has not been blocked.

May be the reason is because my application is responding to any new messages sent by client but If I were only sending messages, my application will be blocked by now.

Back to your questions
1: I don't think their is a limit of how many messages you can send per day but don't "over-send" as it might seem fishy on whatsapp servers and your number might end up being blocked
2: What I understand about this is: do they actually analyse whats the contents of the message then determine whether they can block or not? - If that's the case, maybe in the long term as I have seen guys sending weird stuff for a long time.
3: refer to 1 above.

Hope this is somewhere near what you expected.
Thanks.

**Comment by apdbsa** [comment] 2015-05-10 16:53
Hello, thank you very much for answering ...
* Those 2 million messages are all different numbers?
* If my number is blocked, it can be used again after a while? ... I ask this because the number would be publicized ...
* Your application is a modification of yowsup?

Many thanks ... greetings

**Comment by mutindaz** [comment] 2015-05-10 17:34
- The messages are from different numbers.
- I don't know whether the blocked number might be usable again unless you give it a try and register.
- Yeah its sort of yowsup modification - I basically get the message from yowsup connection, do an http request to my sever I process the message then send the response to the customer. I have also added an event to send a new message created from a web dashboard.

**Comment by aesedepece** [comment] 2015-05-10 17:52
WhatsApp blocks accounts for two months I believe. Then you can register them again as if nothing happened and they are completely reset (1 year free service period starts again).

**Comment by apdbsa** [comment] 2015-05-10 18:07
ok, it helps me a lot ... thank you very much ... I'll go ahead ... Adan you use your 150 chips in the same  ip ... you never had problem with that?

**Comment by domingopa** [comment] 2015-05-10 18:16
Hello @mutindaz your details are fantastic,
Could you describe the scheme of getting that data scrip?

For example:
connect, sync, receive, etc ...

It would be helpful to the community.

thanks

**Comment by aesedepece** [comment] 2015-05-10 21:25
@apdbsa Yep, we've been running all of them from the same IP for months.
In overall there's no record of WhatsApp banning IPs.

**Comment by mgp25** [comment] 2015-05-10 22:03
I think its not a good idea to continue this issue

Cough... (Spammers)...cough

**Comment by aesedepece** [comment] 2015-05-10 22:05
@mgp25 I agree.
I hope everyone here wants to keep WhatsApp free of unsolicited messages selling blue pills and so on.

**Comment by apdbsa** [comment] 2015-05-10 22:41
@aesedepece why you need 150 chips?...what is that usefull for?.. thanks a lot...

**Comment by aesedepece** [comment] 2015-05-11 06:57
@apdbsa The chips are not mine but client's.

**Comment by apdbsa** [comment] 2015-05-11 14:26
@aesedepece Adan, its like i need to do... can you tell me, how many messages you receive and send in each chip?, you do something special?... thank you very much for the help... greetings

**Comment by apdbsa** [comment] 2015-05-11 15:21
@aesedepece Adan, can you tell me your scheme of connection and send... i do this:

        $this->client->sendSync(array($target));
        $this->client->sendMessageComposing($target);
        sleep(1);
        $this->client->sendMessagePaused($target);
        $message = $data;
        $messageID = $this->client->sendMessage($target , $message);
        $this->client->pollMessage();
        $this->client->sendPing();

is this correct? Thanks you very much... greetings

**Comment by apdbsa** [comment] 2015-05-11 15:30
What is the correct scheme for conection, send, and receive?...
I do something like that:
Connect
Sync
Typing
Sleep 1 seg
Send mesage
Receive
exit

Saludos

**Comment by domingopa** [comment] 2015-05-11 15:38
@mgp25 @aesedepece I committed anti-spam 100x100 
;)

**Comment by domingopa** [comment] 2015-05-11 15:39
@apdbsa thanks

**Comment by apdbsa** [comment] 2015-05-11 16:06
Sorry, i fail, my scheme is:

Connect
Sync
Typing
Pausing (to stop typing)
Sleep 1 seg
Send mesage
Receive
exit

Saludos

**Comment by apdbsa** [comment] 2015-05-12 13:03
@mutindaz and @aesedepece  can you tell me your scheme of sending/receiving? this is the most important part in this development... thanks you very much... greetings...

**Comment by dedmen** [comment] 2015-05-12 15:49
Im using
Connect
sync
presence subscribe (kinda spammy cause im doing that for every number ive got in my list)
sleep till message comes in
send reply
sleep till next message and then reply again

which besides the presence subscribe part is exactly what you need i suppose..
If you want to spam Ads to people youll get banned whatever you try to do against it.

**Comment by apdbsa** [comment] 2015-05-12 22:02
@dedmen i dont understand you... what is:
presence subscribe (kinda spammy cause im doing that for every number ive got in my list)
sleep till message comes in

Thanks..

**Comment by apdbsa** [comment] 2015-05-14 15:05
@dedmen what is presence subscribe ?

Thank you.. greetings

**Comment by dedmen** [comment] 2015-05-14 15:06
you can just ignore it... Its basically telling whatsapp to notify me when one of my contacts gets online

**Comment by apdbsa** [comment] 2015-05-14 15:10
@dedmen thank you... you only send message when you receive?

**Comment by dedmen** [comment] 2015-05-14 15:13
yes

**Comment by apdbsa** [comment] 2015-05-14 15:16
with this scheme, how many sims you control? since a long time?

**Comment by dedmen** [comment] 2015-05-14 15:17
2 since 04.12.2014

**Comment by apdbsa** [comment] 2015-05-14 15:20
ah it is wonderful... you have lot of contacts ? in my case I think I'm going to have thousands, i think this is a problem... no?

**Comment by dedmen** [comment] 2015-05-14 15:25
Shouldnt be a problem...

**Comment by apdbsa** [comment] 2015-05-14 15:28
and may send messages without them send? .. I mean if i want to send an update or something to all... this its a problem, no?

**Comment by dedmen** [comment] 2015-05-14 15:35
As far as i know the problem is when youre sending messages to many people that dont have you in their contact list... 
First you cant trust that everyone who writes to you keeps you in their contact list and if you start to send hundeds of message in a short time youll also get blocked.
So no.

**Comment by apdbsa** [comment] 2015-05-14 15:41
yes, my contacts, first add me to yours contact list... because, they send me first... then i respond (like your scheme)...

**Comment by dedmen** [comment] 2015-05-14 15:43
but you dont know if they delete you right after they sent you the message

**Comment by apdbsa** [comment] 2015-05-14 15:48
mm ... that's impossible to know not?

**Closed** 2019-04-28 18:16 UTC
