### ISSUE TITLE
truncated issue

### ISSUE THREAD

**Issue by johnduxx** [tgalal/yowsup#1783] opened 2016-09-29 08:58 UTC
started!
We've already setup a session for this V3 message, letting bundled message fall through...
Received a message that we've previously decrypted, goint to send the delivery receipt myself
DUMP:

Hy
['\n', '\x02', 'H', 'y']
[10, 2, 72, 121]
Traceback (most recent call last):
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\protobuf-3.0.0-py3.6.egg\google\protobuf\internal\python_message.py", line 1082, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\protobuf-3.0.0-py3.6.egg\google\protobuf\internal\python_message.py", line 1104, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\protobuf-3.0.0-py3.6.egg\google\protobuf\internal\decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/python-workspace/run.py", line 21, in <module>
    stack.loop() #this is the program mainloop
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\stacks\yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\stanzaregulator\layer.py", line 52, in processReceived
    self.processReceived()
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\__init__.py", line 189, in receive
    s.receive(data)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 129, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\yowsup2-2.5.0-py3.6.egg\yowsup\layers\axolotl\layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\protobuf-3.0.0-py3.6.egg\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Users\xyzxxxxxxxxxx\AppData\Local\Programs\Python\Python36-32\lib\site-packages\protobuf-3.0.0-py3.6.egg\google\protobuf\internal\python_message.py", line 1088, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.

Process finished with exit code 1

**Comment by ricardojlrufino** [comment] 2016-10-03 19:06
I Got same error:

Python 3.4.3 (default, Oct 14 2015, 20:28:29)

git show
> commit d69c1ff4625f48038018af6eed5478c5a0961241
> Merge: f510d44 70fbe97
> Author: Tarek <tare2.galal@gmail.com>
> Date:   Wed Aug 31 09:56:06 2016 +0200

Error:
https://gist.github.com/ricardojlrufino/cbc3ea6c52094d25a1c1d6d5ebdd8f54

```
DUMP:

Hello
['\n', '\x05', 'H', 'e', 'l', 'l', 'o']
[10, 5, 72, 101, 108, 108, 111]
Traceback (most recent call last):
  File "/media/ricardo/Dados/TEMP/whatspy/lib/python3.4/site-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/media/ricardo/Dados/TEMP/whatspy/lib/python3.4/site-packages/google/protobuf/internal/python_message.py", line 1109, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/media/ricardo/Dados/TEMP/whatspy/lib/python3.4/site-packages/google/protobuf/internal/decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

**Comment by ricardojlrufino** [comment] 2016-10-03 19:16
Duplicate of #1613

**Comment by ricardojlrufino** [comment] 2016-10-05 01:55
Resolution https://github.com/tgalal/yowsup/issues/1613#issuecomment-251235093

**Closed** 2016-10-08 23:15 UTC
