### ISSUE TITLE
Cannot Verify Existing Registration

### ISSUE THREAD

**Issue by varunagrawal** [tgalal/yowsup#480] opened 2014-12-29 10:54 UTC
Hey,

I am trying to verify an existing registration to check whether I need to initiate a new registration flow, but when I try using the yowsup-cli, I get the value

    INFO:yowsup.common.http.warequest:b'{"status":"fail","reason":"incorrect","sms_length":6,
    "voice_length":6}\n'
    voice_length: 6
    status: b'fail'
    sms_length: 6
    reason: b'incorrect'

I use the following request, with ID generated using WART(which gives the same error):

    python3 yowsup-cli.py registration -e --phone 91964xxxxxxx 
    --id %19%83%a8%04a%0f%d4%ed%db%b2%00%a8%f8%82%dab%e7w%11%f6 --cc 91

Also, I am now unable to register as well, constantly getting the fail message with reason "no_routes". I even tried my personal number which has WhatsApp installed, but with no luck. Any clues as to what is going on?

**Comment by aesedepece** [comment] 2015-01-02 16:42
This is likely a duplicate of #370

**Comment by tgalal** [comment] 2015-01-11 15:59
This should be fixed in latest commits. Please reopen if not

**Closed by tgalal** 2015-01-11 15:59 UTC
Labels: registration
