### ISSUE TITLE
No such prekeyRecord! -- general: Disconnected --   image sending upload failed

### ISSUE THREAD

**Issue by BodduSatya** [tgalal/yowsup#2686] opened 2019-04-25 01:43 UTC
Hello tgalal,
1 . Prekeys are not sync ( No such prekeyRecord! )
2. yowsup.3.1.0 reponse is not getting for cli commands & after first message getting general: Disconnected: 
3.Image sending uploading failed.

I 2019-04-25 06:34:23,729 yowsup.layers.network.layer - Connecting to e6.whatsapp.net:443
I 2019-04-25 06:34:24,432 yowsup.axolotl.manager - Loaded 0 unsent prekeys
Auth: Logged in!
W 2019-04-25 06:34:25,668 yowsup.layers.protocol_ib.layer - ignoring edge_routing ib node for now
[connected]:Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/user/yowsup-master/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.1-py3.7.egg/consonance/protocol.py", line 87, in start
    self._machine.finish()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.6.9-py3.7.egg/transitions/core.py", line 383, in trigger
    return self.machine._process(func)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.6.9-py3.7.egg/transitions/core.py", line 1047, in _process
    return trigger()
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.6.9-py3.7.egg/transitions/core.py", line 399, in _trigger
    return self._process(event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.6.9-py3.7.egg/transitions/core.py", line 409, in _process
    if trans.execute(event_data):
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.6.9-py3.7.egg/transitions/core.py", line 266, in execute
    machine.callback(func, event_data)
  File "/usr/local/lib/python3.7/dist-packages/transitions-0.6.9-py3.7.egg/transitions/core.py", line 1005, in callback
    func(*event_data.args, **event_data.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.1-py3.7.egg/consonance/protocol.py", line 57, in _trigger_state_callback
    self._protocol_state_callbacks(self._machine.state)
  File "/home/user/yowsup-master/yowsup/layers/noise/layer.py", line 123, in _on_protocol_state_changed
    self._flush_incoming_buffer()
  File "/home/user/yowsup-master/yowsup/layers/noise/layer.py", line 144, in _flush_incoming_buffer
    self.toUpper(self._wa_noiseprotocol.receive())
  File "/home/user/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup-master/yowsup/layers/coder/layer.py", line 21, in receive
    self.toUpper(node)
  File "/home/user/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup-master/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/home/user/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup-master/yowsup/layers/axolotl/layer_control.py", line 32, in receive
    self.toUpper(protocolTreeNode)
  File "/home/user/yowsup-master/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/home/user/yowsup-master/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/home/user/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 31, in receive
    self.onMessage(protocolTreeNode)
  File "/home/user/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 63, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/home/user/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 75, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/home/user/yowsup-master/yowsup/layers/axolotl/layer_receive.py", line 112, in handlePreKeyWhisperMessage
    enc.getVersion() == 2)
  File "/home/user/yowsup-master/yowsup/axolotl/manager.py", line 164, in decrypt_pkmsg
    plaintext = self._get_session_cipher(senderid).decryptPkmsg(pkmsg)
  File "/usr/local/lib/python3.7/dist-packages/python_axolotl-0.1.42-py3.7.egg/axolotl/sessioncipher.py", line 96, in decryptPkmsg
    unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
  File "/usr/local/lib/python3.7/dist-packages/python_axolotl-0.1.42-py3.7.egg/axolotl/sessionbuilder.py", line 50, in process
    unsignedPreKeyId = self.processV3(sessionRecord, message)
  File "/usr/local/lib/python3.7/dist-packages/python_axolotl-0.1.42-py3.7.egg/axolotl/sessionbuilder.py", line 121, in processV3
    parameters.setOurOneTimePreKey(self.preKeyStore.loadPreKey(message.getPreKeyId()).getKeyPair())
  File "/home/user/yowsup-master/yowsup/axolotl/store/sqlite/liteaxolotlstore.py", line 37, in loadPreKey
    return self.preKeyStore.loadPreKey(preKeyId)
  File "/home/user/yowsup-master/yowsup/axolotl/store/sqlite/liteprekeystore.py", line 21, in loadPreKey
    raise Exception("No such prekeyRecord!")
Exception: No such prekeyRecord!

------------------------------------------------------

I 2019-04-25 06:57:11,899 yowsup.layers.network.layer - Connecting to e8.whatsapp.net:443
I 2019-04-25 06:57:12,438 yowsup.axolotl.manager - Loaded 812 unsent prekeys
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dissononce-0.34.3-py3.7.egg/dissononce/cipher/aesgcm.py", line 18, in decrypt
    return AESGCM(key).decrypt(self.__class__._format_nonce(nonce), ciphertext, ad)
  File "/usr/local/lib/python3.7/dist-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 180, in decrypt
    backend, self, nonce, data, associated_data, 16
  File "/usr/local/lib/python3.7/dist-packages/cryptography/hazmat/backends/openssl/aead.py", line 159, in _decrypt
    raise InvalidTag
cryptography.exceptions.InvalidTag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/user/yowsup-master/yowsup/layers/noise/workers/handshake.py", line 36, in run
    self._protocol.start(self._stream, self._client_config, self._s, self._rs)
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.1-py3.7.egg/consonance/protocol.py", line 82, in start
    result = handshake.perform(client_config, stream, s, rs)
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.1-py3.7.egg/consonance/handshake.py", line 84, in perform
    cipherstatepair = self._start_handshake_xx(stream, client_payload, dissononce_s)
  File "/usr/local/lib/python3.7/dist-packages/consonance-0.1.1-py3.7.egg/consonance/handshake.py", line 128, in _start_handshake_xx
    server_hello.ephemeral + server_hello.static + server_hello.payload, payload_buffer
  File "/usr/local/lib/python3.7/dist-packages/dissononce-0.34.3-py3.7.egg/dissononce/extras/processing/handshakestate_forwarder.py", line 19, in read_message
    return self._handshakestate.read_message(message, payload_buffer)
  File "/usr/local/lib/python3.7/dist-packages/dissononce-0.34.3-py3.7.egg/dissononce/extras/processing/handshakestate_guarded.py", line 110, in read_message
    result = self._handshakestate.read_message(message, payload_buffer)
  File "/usr/local/lib/python3.7/dist-packages/dissononce-0.34.3-py3.7.egg/dissononce/processing/impl/handshakestate.py", line 227, in read_message
    self._rs = self._dh.create_public(self._symmetricstate.decrypt_and_hash(temp))
  File "/usr/local/lib/python3.7/dist-packages/dissononce-0.34.3-py3.7.egg/dissononce/processing/impl/symmetricstate.py", line 133, in decrypt_and_hash
    plaintext = self._cipherstate.decrypt_with_ad(self._h, ciphertext)
  File "/usr/local/lib/python3.7/dist-packages/dissononce-0.34.3-py3.7.egg/dissononce/processing/impl/cipherstate.py", line 73, in decrypt_with_ad
    result = self._cipher.decrypt(self._key, self._nonce, ad, ciphertext)
  File "/usr/local/lib/python3.7/dist-packages/dissononce-0.34.3-py3.7.egg/dissononce/cipher/aesgcm.py", line 20, in decrypt
    raise DecryptFailedException(reason=DecryptFailedException.REASON_INVALID_TAG)
dissononce.exceptions.decrypt.DecryptFailedException

general: Disconnected: 
[offline]:

Thank for this great yowsup

**Comment by stv0g** [comment] 2019-05-01 10:33
Related or duplicate of #2672?

**Comment by tgalal** [comment] 2019-05-04 09:42
yes

**Closed by tgalal** 2019-05-04 09:42 UTC

**Comment by BodduSatya** [comment] 2019-05-04 13:58
Dear tarak,

I tried to upload profile pic, updated successfully , but i am trying to send image  show following error.
i have done the debugging, media hash is generating , but 
/yowsup-master/yowsup/demos/cli/layer.py

```def media_send(self, number, path, mediaType, caption = None):
   .....
    self._sendIq(entity, successFn, errorFn)

   self._sendIq(entity, successFn, errorFn)
```
errorFn is calling 

```errorFn = lambda errorEntity, originalEntity: self.onRequestUploadError(jid, path, errorEntity, originalEntity)```

```self._sendIq(entity, successFn, errorFn)```
statement two times exist , commented last one but no luck.

[connected]: /image send xxxxxxxxxx "/home/XXXX/yowsup-uploads/xxxxx.jpg" "play with coding"
*image_send in layer.py*
media_send
number : xxxxxxxxxxx
path : /home/xxxxxxxx/yowsup-uploads/xxxxxxxx.jpg
mediaType : image
caption : play with coding

*RequestUploadIqProtocolEntity.__init*

filepath /home/xxxx/yowsup-uploads/xxxx.jpg
*_sendIq*

yowsup.layers.logger.layer - tx:
```<iq id="2" type="set" xmlns="w:m" to="s.whatsapp.net">
<media hash="Ce2YxSHwslsrpqglqwkBOgI2XUD+fUDHxfPAIgY+u/k=" type="image" size="86916">
</media>
</iq>```

 yowsup.layers.logger.layer - rx:
```<iq from="s.whatsapp.net" type="error" id="2">
<error code="501" text="feature-not-implemented">
</error>
</iq>```

onRequestUploadError

E yowsup.demos.cli.layer - Request upload for file /home/xxxxx/yowsup-uploads/xxxxx.jpg for xxxxxxxxx@s.whatsapp.net failed
D yowsup.layers.protocol_iq.layer - ping queue size: 1
D yowsup.layers.logger.layer - tx:
```<iq id="3" type="get" xmlns="w:p">
</iq>```

**Comment by paco020295** [comment] 2019-07-22 18:16
> Dear tarak,
> 
> I tried to upload profile pic, updated successfully , but i am trying to send image show following error.
> i have done the debugging, media hash is generating , but
> /yowsup-master/yowsup/demos/cli/layer.py
> 
> ```
>    .....
>     self._sendIq(entity, successFn, errorFn)
> 
>    self._sendIq(entity, successFn, errorFn)
> ```
> 
> errorFn is calling
> 
> `errorFn = lambda errorEntity, originalEntity: self.onRequestUploadError(jid, path, errorEntity, originalEntity)`
> 
> `self._sendIq(entity, successFn, errorFn)`
> statement two times exist , commented last one but no luck.
> 
> [connected]: /image send xxxxxxxxxx "/home/XXXX/yowsup-uploads/xxxxx.jpg" "play with coding"
> _image_send in layer.py_
> media_send
> number : xxxxxxxxxxx
> path : /home/xxxxxxxx/yowsup-uploads/xxxxxxxx.jpg
> mediaType : image
> caption : play with coding
> 
> _RequestUploadIqProtocolEntity.__init_
> 
> filepath /home/xxxx/yowsup-uploads/xxxx.jpg
> __sendIq_
> 
> yowsup.layers.logger.layer - tx:
> 
> ```
> <media hash="Ce2YxSHwslsrpqglqwkBOgI2XUD+fUDHxfPAIgY+u/k=" type="image" size="86916">
> </media>
> </iq>```
> 
>  yowsup.layers.logger.layer - rx:
> ```<iq from="s.whatsapp.net" type="error" id="2">
> <error code="501" text="feature-not-implemented">
> </error>
> </iq>```
> 
> onRequestUploadError
> 
> E yowsup.demos.cli.layer - Request upload for file /home/xxxxx/yowsup-uploads/xxxxx.jpg for xxxxxxxxx@s.whatsapp.net failed
> D yowsup.layers.protocol_iq.layer - ping queue size: 1
> D yowsup.layers.logger.layer - tx:
> ```<iq id="3" type="get" xmlns="w:p">
> </iq>```
> ```

May i ask what did you modify to be able to update profile pic? Please
