### ISSUE TITLE
Config file not created

### ISSUE THREAD

**Issue by fhartavi** [tgalal/yowsup#2785] opened 2019-06-02 11:18 UTC
Sir i registered phone taken request sms and activate number response is here but i cant using number because of config file not created.

I 2019-05-12 12:31:19,862 yowsup.common.http.warequest - b'{"status":"ok","login":"XXX","type":"new","edge_routing_info":"XXX==","chat_dns_domain":"fb","security_code_set":false}\n'
{
"version": 1,
"cc": "44",
"client_static_keypair": "XXXX",
"expid": "XXX",
"fdid": "XXXX",
"id": "XXX",
"mcc": "405",
"mnc": "799",
"phone": "XXX",
"sim_mcc": "000",
"sim_mnc": "000"
}
status: b'ok'
login: b'XXX'
type: b'new'
edge_routing_info: b'XXX'

**Comment by tgalal** [comment] 2019-06-02 11:57
please follow bug report template. Closing for lack of information and possible duplicate of  #2781

**Closed by tgalal** 2019-06-02 11:57 UTC
