### ISSUE TITLE
Exception raised for type="picture" notify="EmaZel"

### ISSUE THREAD

**Issue by lorenzoPrimi** [tgalal/yowsup#592] opened 2015-01-28 09:00 UTC
[offline]:/L
Auth: Logged in!
[connected]:Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.2.15', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 304, in <module>
    if not parser.process():
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 223, in process
    self.startCmdline()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 249, in startCmdline
    stack.start()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/demos/cli/stack.py", line 28, in start
    self.stack.loop(timeout = 0.5, discrete = 0.5)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/stacks/yowstack.py", line 162, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/network/layer.py", line 48, in handle_read
    self.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/network/layer.py", line 55, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
    self.processReceived()
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 56, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 161, in receive
    s.receive(data)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 102, in receive
    recv(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/protocol_notifications/layer.py", line 24, in recvNotification
    self.raiseErrorForNode(node)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 118, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification retry="4" from="34629936456@s.whatsapp.net" t="1422398514" offline="4" type="picture" id="3762986897" notify="EmaZel">
<delete jid="34629936456@s.whatsapp.net">
</delete>
</notification>

**Comment by jlguardi** [comment] 2015-01-28 09:15
Are you sure this notification produced your error? I've gotten this kind of error on "web" notifications as reported in #585.

**Comment by lorenzoPrimi** [comment] 2015-01-28 09:19
I copied and pasted what was in the terminal but there is a piece of log missing:

  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.2.15-py2.7.egg/yowsup/layers/__init__.py", line 118, in raiseErrorForNode
    raise ValueError("Unimplemented notification type %s " % node)
ValueError: Unimplemented notification type <notification from="34629936456@s.whatsapp.net" notify="EmaZel" offline="0" type="picture" id="3762986897" t="1422398514">
<delete jid="34629936456@s.whatsapp.net">
</delete>
</notification>

**Comment by lorenzoPrimi** [comment] 2015-01-28 09:20
I copied and pasted what was in the terminal but there is a piece of log missing:
<notification from="34629936456@s.whatsapp.net" notify="EmaZel" offline="0" type="picture" id="3762986897" t="1422398514">
<delete jid="34629936456@s.whatsapp.net">
</delete>
</notification>

**Comment by dedmen** [comment] 2015-01-29 19:40
Duplicate of #561
hotfix:
replace
        if node["type"] == "picture":
            if node.getChild("set"):
                self.toUpper(PictureNotificationProtocolEntity.fromProtocolTreeNode(node))
            else:
                self.raiseErrorForNode(node)

with
        if node["type"] == "picture":
            if node.getChild("set"):
                self.toUpper(PictureNotificationProtocolEntity.fromProtocolTreeNode(node))
            elif node.getChild("delete"):
                pass
            else:
                self.raiseErrorForNode(node)

**Comment by leninmhs** [comment] 2015-02-06 11:18
after apply this change run again python setup.py install

**Comment by dedmen** [comment] 2015-02-06 14:34
Reinstall is only required if you did it before. If you directly execute yowsup-cli in the yowsup directory it works without reinstalling.

**Closed** 2015-05-11 05:56 UTC
Labels: feature
