### ISSUE TITLE
ImportError: cannot import name ProtocolTreeNode

### ISSUE THREAD

**Issue by rodrigoorrego** [tgalal/yowsup#2120] opened 2017-06-19 04:08 UTC
tried to merge jguardi's branch with tgalal's and now I'm having this issue:

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from layer                                     import EchoLayer
  File "/root/data/Yowsup_Atlas/layer.py", line 16, in <module>
    from yowsup.layers.protocol_media.picture              import YowMediaPictureLayer              #descarga imagen
  File "/usr/local/lib/python2.7/dist-packages/yowsup/layers/protocol_media/picture.py", line 2, in <module>
    from yowsup import ProtocolTreeNode
ImportError: cannot import name ProtocolTreeNode

someone can help me please? thanks for the attention!

**Comment by cinatic** [comment] 2017-06-19 08:18
looks very fked up, because it failed to import it because picture is imported in ProtocolTreeNode or in some dependencies above. To solve this you need to check if picture (or it base classes) is used in ProtocolTreeNode or in any other module related to it.

I merged the media encryption things from tgalal if you are interested i can commit the changes in my fork.

**Comment by noahfx** [comment] 2018-01-06 18:05
I've found this test running yowsup with python3.6 and couldn't reproduce it with python2.7
I have submitted a PR fixing this.

**Closed** 2019-05-07 18:30 UTC
